version: '3'
services:
  odoo:
    image: odoo:16
    ports:
      - "8069:8069"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
